### ISSUE TITLE
Scanning images so slow

### ISSUE THREAD

**Issue by nguyentheloc-eithan** [albertovalerio/face-recognition-auth-reactjs#2]
I dont know why I register by posting Images and it scanning for so long
![image](https://github.com/user-attachments/assets/9a44dc31-eac7-4e00-b4f2-ef5a1840129a)

**Comment by albertovalerio** [comment]
What does "so long" mean? 1 min? 10 min? 2 hours?
Anyways the first scan takes a bit longer because the model is loaded into the browser cache, the next scans are very fast! So it depends also on the memory cache you have available. The tests I did on my old Mackbook Pro (2019) 16GB RAM, took 4/5 secs for the first scan and less than 1 sec for the next ones.

**Comment by nguyentheloc-eithan** [comment]
yeah, it take about 3-5 mins on windows, but when i run it on Linux, it's much more faster. Thanh you so much
